### ISSUE TITLE
In K8s 1.22/1.24 and later, SAs don’t automatically get a secret with a token

### ISSUE THREAD

**Issue by skitt** [submariner-io/subctl#102]
`subctl` needs to create a number of service accounts, and relies on Kubernetes to create an associated secret and token. Starting with Kubernetes 1.22, secret/token generation is no longer guaranteed, and it is disabled by default starting with Kubernetes 1.24.

`subctl` needs to be fixed to create a secret after creating a service account, and wait for the token on the secret if necessary. See https://kubernetes.io/docs/concepts/configuration/secret/#service-account-token-secrets for details.

Without this, Submariner can no longer be installed on Kubernetes 1.24 or later.

The fix will have to be backported to 0.12.

**Comment by liggitt** [comment]
Alternatively, if a permanent token is not required, the [TokenRequest](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-request-v1/) API is preferred for directly obtaining a time-bound token.

**Comment by vthapar** [comment]
Working on the fix, which is to create the Secret with relevant type and annotation. Currently semi blocked by lack of a 1.24.0 deployment to reproduce the issue and test the changes.

PR for K8s 1.24 support in kind https://github.com/submariner-io/shipyard/pull/825

**Comment by nyechiel** [comment]
@vthapar can you please share an update on this?
