### ISSUE TITLE
subctl gather all only captures connectivity data

### ISSUE THREAD

**Issue by vthapar** [submariner-io/subctl#1083]
**What happened**:
`subctl gather all` is unsupported flag but doesn't throw any error or warning.

```
Gathering information from cluster "amagrawa-mc2"
 ⚠ Gathering connectivity logs 
 ✓ Found 3 pods matching label selector "app=submariner-gateway"
 ✓ Found 6 pods matching label selector "app=submariner-routeagent"
 ✓ Found 3 pods matching label selector "app=submariner-metrics-proxy"
 ⚠ Found logs for previous instances of pod submariner-metrics-proxy-cdbxp
 ⚠ Found logs for previous instances of pod submariner-metrics-proxy-gp2sm
 ✓ Found 3 pods matching label selector "app=submariner-metrics-proxy"
 ⚠ Found logs for previous instances of pod submariner-metrics-proxy-cdbxp
 ⚠ Found logs for previous instances of pod submariner-metrics-proxy-gp2sm
 ✓ Found 3 pods matching label selector "app=submariner-globalnet"
 ✓ Found 1 pods matching label selector "app=submariner-addon"
```
**What you expected to happen**:
It should throw an error because `all` is not a supported flag for `subctl gather`.
**How to reproduce it (as minimally and precisely as possible)**:
Run `subctl gather all`

**Comment by tpantelis** [comment]
`all` is treated as an arg and not a flag since it isn't preceded by `--`. We ignore args but we should ensure no args are passed as is done for `verify`.

`subctl gather all` is the same as `subctl gather` which captures everything.
