### ISSUE TITLE
subctl upgrade failed - failed to upgrade from 0.17.1 to 0.18.0-rc0

### ISSUE THREAD

**Issue by maayanf24** [submariner-io/subctl#1148]
**What happened**:
`subctl upgrade --to-version 0.18.0-rc0` failed to upgrade `submariner-gateway` pod

**What you expected to happen**:
All of submariner components should be upgraded to requested version

**How to reproduce it (as minimally and precisely as possible)**:
use subctl 0.17.1 to deploy submariner
run: `subctl upgrade --to-version 0.18.0-rc0` 

**Anything else we need to know?**:
Output from: `kubectl describe daemonset submariner-gateway  -n submariner-operator`:
`
Events:
  Type     Reason        Age                From                  Message
  ----     ------        ----               ----                  -------
  Warning  FailedCreate  7s (x20 over 38m)  daemonset-controller  Error creating: pods "submariner-gateway-" is forbidden: volume with secret.secretName="broker-secret-4647f" is not allowed because service account submariner-gateway does not reference that secret
`

output from: `kubectl get secrets -n submariner-operator`:
`
NAME                   TYPE     DATA   AGE
broker-secret-4647f    Opaque   3      26m
submariner-ipsec-psk   Opaque   1      26m
`

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by tpantelis** [comment]
The broker secret was renamed to "_submariner-broker-secret_" by https://github.com/submariner-io/subctl/pull/1128 so we need to migrate it.
