### ISSUE TITLE
subctl cloud prepare fails with OCP 4.16

### ISSUE THREAD

**Issue by vthapar** [submariner-io/subctl#1149]
**What happened**:
`subctl cloud prepare aws` fails with 0.18.0-rc build on OCP 4.16 clusters.

**What you expected to happen**:
Cloud prepare should run successfully.

**How to reproduce it (as minimally and precisely as possible)**:
Use `subctl` version `0.18.0-rc0` to run `subctl cloud prepare`

**Anything else we need to know?**:
Error log:

```
subctl cloud prepare aws --infra-id $infra_id --region $region --profile aws-acm-subm
 ✓ Preparing AWS cloud for Submariner deployment 
 ✓ Initializing AWS connectivity
 ✓ Retrieving VPC ID 
 ✓ Retrieved VPC ID vpc-04931defb4f5fdb83
 ✗ Validating pre-requisites 
 ✗ Unable to validate prerequisites: [security group {infraID}-worker-sg not found, insufficient number of public subnets (0) to deploy 1 Submariner gateway(s)]
 ✗ Failed to prepare AWS cloud: unable to validate prerequisites: [security group {infraID}-worker-sg not found, insufficient number of public subnets (0) to deploy 1 Submariner gateway(s)]
```
**Environment**:
Fails with subctl versions `v0.18.0-rc0`, `v0.17.1`

subctl cloud prepare aws --infra-id $infra_id --region $region --profile aws-acm-subm ✓ Preparing AWS cloud for Submariner deployment 
 ✓ Initializing AWS connectivity
 ✓ Retrieving VPC ID 
 ✓ Retrieved VPC ID vpc-0079e48203562241c
 ✗ Validating pre-requisites 
 ✗ Unable to validate prerequisites: [security group {infraID}-worker-sg not found, insufficient number of public subnets (0) to deploy 1 Submariner gateway(s)]
 ✗ Failed to prepare AWS cloud: unable to validate prerequisites: [security group {infraID}-worker-sg not found, insufficient number of public subnets (0) to deploy 1 Submariner gateway(s)]

subctl version: v0.18.0-rc0

- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- Install tools:
- Others: OCP Version 4.16.0-rc3

**Comment by yboaron** [comment]
Addressed by 
https://github.com/submariner-io/cloud-prepare/pull/949

And also backported to 0.18 and 0.17
https://github.com/submariner-io/cloud-prepare/pull/963
https://github.com/submariner-io/cloud-prepare/pull/964
