### ISSUE TITLE
Subctl join fails (error updating the privileged SCC) on ROSA cluster

### ISSUE THREAD

**Issue by yboaron** [submariner-io/subctl#117]
**What happened**:

I tried to deploy Submariner on ROSA cluster using subctl : 

subctl join --kubecontext <xx>  broker-info.subm  --clusterid aws-rosa  --load-balancer

Deployment failed with the following error : 

Join error :

✗ Deploying the Submariner operator 
 ✓ Created operator CRDs
 ✓ Created operator namespace: submariner-operator
 ✓ Created operator service account and role
Error deploying the operator: error updating the SCC resource: error updating OpenShift privileged SCC: admission webhook "scc-validation.managed.openshift.io" denied the request: Modifying default SCCs [anyuid hostaccess hostmount-anyuid hostnetwork node-exporter nonroot privileged restricted] is not allowed

subctl version: v0.12.1

**What you expected to happen**:

Successful deployment 

**How to reproduce it (as minimally and precisely as possible)**:
see above 

**Anything else we need to know?**:
As part of Submariner deployment we update [1]  the privileged SCC users with the Submariner Service Accounts , and in ROSA clusters seems that the admission webhook controller is rejecting any changes to the privileged SCC

I was able to  add user to privileged SCC using [2] command

[1] 
https://github.com/submariner-io/subctl/blob/devel/pkg/scc/update.go#L40 

[2]
oc adm policy add-scc-to-user privileged system:serviceaccount:submariner-operator:submariner-gateway

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by nyechiel** [comment]
Note that this is probably not unique to LB service, and something we should address regardless.

**Comment by yboaron** [comment]
> Note that this is probably not unique to LB service, and something we should address regardless.

Correct, this is not unique to LB, we are unable to add Submariner Service accounts to privileged SCC users, and the root reason seems to be that the access webhook controller rejects any changes to the privileged SCC

**Comment by sridhargaddam** [comment]
We can try to identify how users are added when the following command is used and update our Submariner deployment steps accordingly, so that we will have a generic fix for all clusters.

```
oc adm policy add-scc-to-user privileged system:serviceaccount:submariner-operator:submariner-gateway
```

**Comment by mkolesnik** [comment]
Do we really want to be touching these pre-requisites on the infra, or can we just have it documented as a pre-requisite and instruct users to do it for installing Sumbariner on ROSA?

**Comment by sridhargaddam** [comment]
> Do we really want to be touching these pre-requisites on the infra, or can we just have it documented as a pre-requisite and instruct users to do it for installing Sumbariner on ROSA?

This is not specific to ROSA and we might hit this problem in any OCP cluster where the admission webhook controller is enabled before installing Submariner. If we understand how `oc adm policy add-scc-to-user ...` works in such deployments and tweak Submariner deployment accordingly we will have less pre-requisites from the platform.

**Comment by yboaron** [comment]
>Do we really want to be touching these pre-requisites on the infra, or can we just have it documented as a pre-requisite and instruct users to do it for installing Sumbariner on ROSA?

Yeah, don't think it's about infra changes either, it's about making sure that submariner pods have the necessary permissions.
As a short term solution, I guess we can continue with the current approach and document the workaround for the relevant platforms.

**Comment by yboaron** [comment]
> If we understand how oc adm policy add-scc-to-user ... works in such deployments and tweak Submariner deployment accordingly we will have less pre-requisites from the platform.

IIUC, [oc adm policy sources](https://github.com/openshift/oc/blob/master/pkg/cli/admin/policy/modify_scc.go#L230), it first creates (if they don't exist yet) clusterrole and clusterrolebinding resources named system:openshift:scc:privileged, (check [1] for more details) and adds a new entry to subjects section in system:openshift:scc:privileged  clusterrolebinding.

I don't think it's a good idea to rely on the resources created by oc adm policy cli as we might hit some race issues. 
Did you mean to follow the method used in oc cli but with new clusterrole and clusterrolbinding resources ?


[1] 

$ oc get clusterrole  system:openshift:scc:privileged -o yaml 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2022-06-13T13:56:23Z"
  name: system:openshift:scc:privileged
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: d04b82fb-a8c4-4272-9beb-3dba8bf2666f
  resourceVersion: "1293"
  uid: 7793fa4c-9cbd-43f2-bd27-ec530481ba2c
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use

$ oc get clusterrolebinding  system:openshift:scc:privileged -o yaml 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2022-06-21T19:45:27Z"
  name: system:openshift:scc:privileged
  resourceVersion: "53533937"
  uid: 67d249e4-46ea-4571-a678-2fa290070e97
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: submariner-routeagent
  namespace: submariner-operator
- kind: ServiceAccount
  name: submariner-operator
  namespace: submariner-operator
- kind: ServiceAccount
  name: default
  namespace: submariner-operator

**Comment by yboaron** [comment]
[1] is the relevant SCC validation PR (for managed clusters) 

[1]
https://github.com/openshift/managed-cluster-validating-webhooks/pull/176
