### ISSUE TITLE
Add platform information to subctl gather

### ISSUE THREAD

**Issue by skitt** [submariner-io/subctl#123]
Now that Submariner ships images for multiple architectures, it would be useful for `subctl`’s “informative” commands to include the architecture used for each component.

**Comment by jinglina** [comment]
It is quite confused when k8s cluster is a multi-arch platform . What will show when tring to show architectures info using `subctl `command,  showing different arch info in different nodes among same cluster? @dfarrell07 @skitt

**Comment by skitt** [comment]
#901 adds the architecture to the output of `show versions`.
