### ISSUE TITLE
Error in running subctl diagnose from a pod - missing permissions.

### ISSUE THREAD

**Issue by tomer-shefler** [submariner-io/subctl#129]
**What happened**:
During subctl diagnose from inside a pod, 
the test: checking sumariner pods test failed 

• Checking Submariner pods  ...
 ✗ Checking Submariner pods
 ✗ Error obtaining Deployment ["submariner-lighthouse-agent" "deployments.apps \"submariner-lighthouse-agent\" is forbidden: User \"system:serviceaccount:submariner-operator:submariner-diagnose\" cannot get resource \"deployments\" in API group \"apps\" in the namespace \"submariner-operator\""]: %!v(MISSING)
 ✗ Error obtaining Deployment ["submariner-lighthouse-coredns" "deployments.apps \"submariner-lighthouse-coredns\" is forbidden: User \"system:serviceaccount:submariner-operator:submariner-diagnose\" cannot get resource \"deployments\" in API group \"apps\" in the namespace \"submariner-operator\""]: %!v(MISSING)

**What you expected to happen**:
Test was expected to succeed

**How to reproduce it (as minimally and precisely as possible)**:
Run subctl diagnose from a pod according to this manual:
https://submariner.io/operations/deployment/subctl/#running-subctl-diagnose-from-a-pod-in-cluster

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by tomer-shefler** [comment]
@mkolesnik @vthapar

**Comment by vthapar** [comment]
RBAC for diagnose pod was added in https://github.com/submariner-io/submariner-operator/commit/90af63ca0dde2d72b38a4971b1610b9ed129db90

This looks like during refactoring code to new subctl repo some of these changes were missed/lost.

**Comment by dfarrell07** [comment]
@tomer-shefler You might be interested in handling this yourself? It should be fairly clearly scoped, moving the RBAC from the operator to subctl.

**Comment by tpantelis** [comment]
The permissions have been addressed and we have a [system test](https://github.com/submariner-io/subctl/pull/240) to verify it.
