### ISSUE TITLE
Error in running subctl diagnose from a pod - self pod appears to be 'pending'

### ISSUE THREAD

**Issue by tomer-shefler** [submariner-io/subctl#130]
**What happened**:
During subctl diagnose from inside a pod,
the test: checking sumariner pods test failed
✗ Pod ["submariner-diagnose-f4lcq" "Pending"] is not running. (current state is %!v(MISSING))

**What you expected to happen**:
The test was expected to succeed

**How to reproduce it (as minimally and precisely as possible)**:
Run subctl diagnose from a pod according to this manual:
https://submariner.io/operations/deployment/subctl/#running-subctl-diagnose-from-a-pod-in-cluster

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by tomer-shefler** [comment]
@mkolesnik @vthapar

**Comment by vthapar** [comment]
`subctl diagnose` checks status of *all* pods in `submariner-operator` namespace. Sometimes diagnose pod's status is not updated by the time we check for pod status, resulting in this error. This is mostly harmless, but can confuse the users. Simple fix would be to ignore diagnose pod when checking status in diagnose.

**Comment by mkolesnik** [comment]
can we only check pods with a certain known label?

or have a label to ignore pods by this check?

this would be much more explicit, and we can utilize k8s filtering instead of relying on pod names (which can obviously change)
