### ISSUE TITLE
Submariner Verification Failed

### ISSUE THREAD

**Issue by caatclaudia** [submariner-io/subctl#134]
I'm trying to deploy submariner in K3s, so I use this [documentation](https://submariner.io/getting-started/quickstart/k3s/) and I use the exact same commands (just add the label "`submariner.io/gateway=true`" on the nodes to the gateway could be deployed). But when I use the command `KUBECONFIG=kubeconfig.cluster-a:kubeconfig.cluster-b subctl verify --kubecontexts cluster-a,cluster-b --only service-discovery,connectivity --verbose` to test this implementation the output is what is in the file "logsSubmariner.txt".
[logsSubmariner.txt](https://github.com/submariner-io/subctl/files/8999757/logsSubmariner.txt)

File "show.txt" shows the output of the command "`subctl show all`", file "diagonise.txt" show the output of the command "`subctl diagonise all`". These commands were executed in cluster-a.

[diagonise.txt](https://github.com/submariner-io/subctl/files/8999756/diagonise.txt)
[show.txt](https://github.com/submariner-io/subctl/files/8999776/show.txt)

![image](https://user-images.githubusercontent.com/56655085/176149061-328ce138-d0ba-4162-8a68-8736095317df.png)

**Comment by dfarrell07** [comment]
Sorry for missing this! We need to decide if we have devs with resources to support K3s well, currently we don't really seem to. Raised https://github.com/submariner-io/submariner/issues/2108 to track.

**Comment by dfarrell07** [comment]
If you still want to try with K3s maybe let's discuss there or on Slack, but for now closing this.
