### ISSUE TITLE
Operator deployment should fail if any resource is not created

### ISSUE THREAD

**Issue by Jaanki** [submariner-io/subctl#139]
**What happened**:
submariner deployment went through fine even if SAs/roles/RBs/cluster roles/cluster role binding was not created for operator/submariner/LH.

**What you expected to happen**:
It should have failed the instance when one of the resources for any of the services was not created.

**How to reproduce it (as minimally and precisely as possible)**:
See https://github.com/Jaanki/submariner-operator/pull/8 for reference.

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by dfarrell07** [comment]
Talking to @Jaanki, this is actually working as it's supposed to. Closing.
