### ISSUE TITLE
`subctl uninstall` remove the wrong cluster

### ISSUE THREAD

**Issue by maayanf24** [submariner-io/subctl#15]
**What happened**:
running `subctl uninstall output/kubeconfigs/kind-config-cluster2` removes cluster 1

```
subctl uninstall output/kubeconfigs/kind-config-cluster2
? This will completely uninstall Submariner from the cluster "cluster1". Are you sure you want to continue? Yes
 ✓ Checking if the connectivity component is installed on cluster "cluster1"
 ✓ The connectivity component is installed on cluster "cluster1"
 ✓ Deleting the Submariner resource - this may take some time 
 ✓ Deleting the Submariner cluster roles and bindings on cluster "cluster1" 
 ✓ Deleted the "submariner-diagnose" cluster role and binding
 ✓ Deleted the "submariner-gateway" cluster role and binding
 ✓ Deleted the "submariner-globalnet" cluster role and binding
 ✓ Deleted the "submariner-lighthouse-agent" cluster role and binding
 ✓ Deleted the "submariner-lighthouse-coredns" cluster role and binding
 ✓ Deleted the "submariner-networkplugin-syncer" cluster role and binding
 ✓ Deleted the "submariner-operator" cluster role and binding
 ✓ Deleted the "submariner-routeagent" cluster role and binding
 ✓ Deleting the Submariner namespace "submariner-operator" on cluster "cluster1"
 ✓ Deleting the broker namespace "submariner-k8s-broker" on cluster "cluster1"
 ✓ Deleting the Submariner custom resource definitions on cluster "cluster1"
 ✓ Deleted the "brokers.submariner.io" custom resource definition
 ✓ Deleted the "clusterglobalegressips.submariner.io" custom resource definition
 ✓ Deleted the "clusters.submariner.io" custom resource definition
 ✓ Deleted the "endpoints.submariner.io" custom resource definition
 ✓ Deleted the "gateways.submariner.io" custom resource definition
 ✓ Deleted the "globalegressips.submariner.io" custom resource definition
 ✓ Deleted the "globalingressips.submariner.io" custom resource definition
 ✓ Deleted the "servicediscoveries.submariner.io" custom resource definition
 ✓ Deleted the "submariners.submariner.io" custom resource definition
 ✓ Unlabeling gateway nodes on cluster "cluster1"

```

**What you expected to happen**:
cluster2 should be removed

**How to reproduce it (as minimally and precisely as possible)**:
`subctl uninstall output/kubeconfigs/kind-config-cluster2`

**Anything else we need to know?**:

**Environment**:
kind, with globalnet
subctl version: 0.13.0-m1

**Comment by maayanf24** [comment]
same happens when running without globalnet, using vxlan cable driver.
same for running on Openshift with AWS:
`subctl uninstall cluster-b/auth/kubeconfig
? This will completely uninstall Submariner from the cluster "maafried-cluster-a". Are you sure you want to continue? No
`

**Comment by sridhargaddam** [comment]
@maayanf24 According to the help, we have to use the --kubeconfig flag.

```
[sgaddam@localhost submariner]$ subctl uninstall -h
This command uninstalls Submariner and its components

Usage:
  subctl uninstall [flags]

Flags:
  -h, --help                help for uninstall
      --kubeconfig string   absolute path(s) to the kubeconfig file(s)
  -n, --namespace string    namespace in which Submariner is installed (default "submariner-operator")
  -y, --yes                 automatically answer yes to confirmation prompt
[sgaddam@localhost submariner]$ 

```

Can you try `subctl uninstall --kubeconfig output/kubeconfigs/kind-config-cluster2`

**Comment by maayanf24** [comment]
`--kubeconfig`  must be a mandatory flag, I run `subctl uninstall` twice without making any changes to `KUBCONFIG` and for each time the result is different:
```
subctl uninstall
? This will completely uninstall Submariner from the cluster "cluster2". Are you sure you want to continue? No
[maafried@localhost submariner-operator]$ subctl uninstall
? This will completely uninstall Submariner from the cluster "cluster1". Are you sure you want to continue? No

```

**Comment by skitt** [comment]
https://github.com/submariner-io/enhancements/pull/101 but it wasn’t approved ;-).

**Comment by mkolesnik** [comment]
> `--kubeconfig` must be a mandatory flag, I run `subctl uninstall` twice without making any changes to `KUBCONFIG` and for each time the result is different:
> 

How does that make sense to make it mandatory?

It seems your initial mistake was thinking that the command accepts an argument, when  it clearly doesn't so it's not really a bug then IMO.

**Comment by tpantelis** [comment]
> > `--kubeconfig` must be a mandatory flag, I run `subctl uninstall` twice without making any changes to `KUBCONFIG` and for each time the result is different:
> 
> How does that make sense to make it mandatory?
> 
> It seems your initial mistake was thinking that the command accepts an argument, when it clearly doesn't so it's not really a bug then IMO.

yeah it's user error. The prompt also indicates which cluster it is uninstalling. But, to alleviate such user error, we could fail if an unexpected argument is provided.

**Comment by mkolesnik** [comment]
> yeah it's user error. The prompt also indicates which cluster it is uninstalling. But, to alleviate such user error, we could fail if an unexpected argument is provided.

That should be a general goal then, not just for uninstall, right?

**Comment by nyechiel** [comment]
I think we should close this and reopen if users complain. I always export the kubeconfig and run `subctl uninstall` without any flags and never faced any issue. Also, there is a clear output that indicates what's going to happen, so users should review before picking "yes".

**Comment by maayanf24** [comment]
had been discussed on scrub meeting and decided to close
can be reopen if needed
