### ISSUE TITLE
gather should collect the routes in table 100 when using VxLAN cable-driver

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/subctl#159]
**What happened**:
When Submariner is deployed with VxLAN cable-driver, the output of "subctl gather ..." does not include routes programmed in table 100 from the Gateway nodes. This is an important information which will help us while debugging any connection issues with VxLAN cable-driver.

**Comment by nyechiel** [comment]
@sridhargaddam thanks for reporting this bug. It sounds like a small change with large benefit. Since VXLAN is not the default, I don't feel like we should delay the 0.13.0 release because of this, would you agree?

**Comment by sridhargaddam** [comment]
> @sridhargaddam thanks for reporting this bug. It sounds like a small change with large benefit. Since VXLAN is not the default, I don't feel like we should delay the 0.13.0 release because of this, would you agree?

Agree. No need to delay the 0.13 release

**Comment by nyechiel** [comment]
@sridhargaddam @tpantelis @skitt FYI, Yossi pushed a PR to address this issue. I have added it to the 0.13 board because we don't have a board for 0.14 as of yet. Just to be explicitly clear - we can get it reviewed/merged for devel, but this should not block or delay 0.13.0.

**Comment by nyechiel** [comment]
> @sridhargaddam @tpantelis @skitt FYI, Yossi pushed a PR to address this issue. I have added it to the 0.13 board because we don't have a board for 0.14 as of yet. Just to be explicitly clear - we can get it reviewed/merged for devel, but this should not block or delay 0.13.0.

There is actually a new board for 0.14. Moving it.
