### ISSUE TITLE
subctl diagnose deployment should skip diagnose/test pods in its validation

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/subctl#182]
**What happened**:
Recently we modified the default namespace in `subctl diagnose ...` command to `submariner-operator` to avoid warnings when running on K8s 1.23+ clusters that includes podSecurity admission controller enabled.

While this is fine, if any of the diagnose pods failed to terminate properly (or in the process of getting deleted), `subctl diagnose deployment` is checking the status of all the pods running in `submariner-operator` namespace and reporting error for these diagnose/test pods.

```
Checking Submariner pods
Pod "01f4a817375d3bc08e7dcffaccb791f349013c992ff603fe6e0cd17983sbrmr" is not running. (current state is Succeeded)
Pod "query-iface-list4pms8" is not running. (current state is Pending)
Pod "validate-sniffer44jkv" is not running. (current state is Pending)
```

Seen with subctl 0.13.0 binary.

**Comment by mkolesnik** [comment]
This was fixed by #183
