### ISSUE TITLE
Add `subctl diagnose pre-install`

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/subctl#267]
**What would you like to be added**:
Add a `subctl diagnose pre-install` command which checks that the infrastructure supports installing Submariner by checking:

* Gateway nodes are set-up.
  * Kube proxy, if there, doesn't run in IPVS mode - as it's currently not supported.
* The broker is reachable from the cluster.
* K8s version is supported.
* The CNI is supported.
* Conflicts with existing clusters in the clusterset.
  * CIDRs should be distinct, unless the clusterset is using globalnet.
* The necessary ports are open.
  * On the gateway, when not using Load Balancer, the cable driver port(s).
  * On the nodes, when not using OVN, the vxlan port.

**Why is this needed**:
As a user of Submariner, it would be useful in a myriad of situations to have a tool capable of testing the Kubernetes infrastructure
where Submariner is to be installed.
The tool should check all of Submariner's pre-requisites from the infrastructure, and report any deficiencies.
It would be nice if the tool can also offer guidance for the deficiencies, so that the user can address them and install Submariner successfully.

**Comment by mkolesnik** [comment]
Enhancement proposal @ https://github.com/submariner-io/enhancements/pull/134

**Comment by dfarrell07** [comment]
Mike says there's a newer issue for this (and if not, he will find and reopen this).
