### ISSUE TITLE
Meet emerging K8s pod security requirements

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/subctl#27]
While running subctl diagnose commands on an OCP 4.11 version, the following warnings were noticed. The command seems to run fine, but we have to tweak the Security Context to fix these warnings.

```
subctl diagnose all
Cluster "amagrawa-c1-411"
 ✓ Checking Submariner support for the Kubernetes version
 ✓ Kubernetes version "v1.23.3+69213f8" is supported
 
 ✓ Checking Submariner support for the CNI network plugin
 ✓ The detected CNI network plugin ("OpenShiftSDN") is supported
 
 ✓ Checking gateway connections
 ✓ All connections are established
 
 ✓ Checking Submariner pods
 ✓ All Submariner pods are up and running
 
 ✓ Non-Globalnet deployment detected - checking if cluster CIDRs overlap
 ✓ Clusters do not have overlapping CIDRs
 
⠈⡱ Checking Submariner support for the kube-proxy mode W0516 16:30:50.377740   38759 warnings.go:67] would violate PodSecurity "restricted:latest": non-default capabilities (container "query-iface-list" must not include "NET_ADMIN", "NET_RAW" in securityContext.capabilities.add), host namespaces (hostNetwork=true), allowPrivilegeEscalation != false (container "query-iface-list" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "query-iface-list" must set securityContext.capabilities.drop=["ALL"]; container "query-iface-list" must not include "NET_ADMIN", "NET_RAW" in securityContext.capabilities.add), runAsNonRoot != true (pod or container "query-iface-list" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "query-iface-list" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
 ✓ Checking Submariner support for the kube-proxy mode
 ✓ The kube-proxy mode is supported
 
⠈⠑ Checking the firewall configuration to determine if the metrics port (8080) is allowed W0516 16:30:58.959021   38759 warnings.go:67] would violate PodSecurity "restricted:latest": non-default capabilities (container "validate-sniffer" must not include "NET_ADMIN", "NET_RAW" in securityContext.capabilities.add), host namespaces (hostNetwork=true), allowPrivilegeEscalation != false (container "validate-sniffer" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "validate-sniffer" must set securityContext.capabilities.drop=["ALL"]; container "validate-sniffer" must not include "NET_ADMIN", "NET_RAW" in securityContext.capabilities.add), runAsNonRoot != true (pod or container "validate-sniffer" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "validate-sniffer" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
⢄⡱ Checking the firewall configuration to determine if the metrics port (8080) is allowed W0516 16:31:05.487814   38759 warnings.go:67] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "validate-client" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "validate-client" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "validate-client" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "validate-client" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
 ✓ Checking the firewall configuration to determine if the metrics port (8080) is allowed
 ✓ The firewall configuration allows metrics to be retrieved from Gateway nodes
 
⠊⠁ Checking the firewall configuration to determine if VXLAN traffic is allowed W0516 16:31:16.307616   38759 warnings.go:67] would violate PodSecurity "restricted:latest": non-default capabilities (container "validate-sniffer" must not include "NET_ADMIN", "NET_RAW" in securityContext.capabilities.add), host namespaces (hostNetwork=true), allowPrivilegeEscalation != false (container "validate-sniffer" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "validate-sniffer" must set securityContext.capabilities.drop=["ALL"]; container "validate-sniffer" must not include "NET_ADMIN", "NET_RAW" in securityContext.capabilities.add), runAsNonRoot != true (pod or container "validate-sniffer" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "validate-sniffer" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
⢄⡱ Checking the firewall configuration to determine if VXLAN traffic is allowed W0516 16:31:22.879381   38759 warnings.go:67] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "validate-client" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "validate-client" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "validate-client" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "validate-client" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
 ✓ Checking the firewall configuration to determine if VXLAN traffic is allowed
 ✓ The firewall configuration allows VXLAN traffic
 
 ✓ Globalnet is not installed - skipping
 
Skipping inter-cluster firewall check as it requires two kubeconfigs. Please run "subctl diagnose firewall inter-cluster" command manually.
```

**Comment by sridhargaddam** [comment]
Similar warnings are seen even when e2e tests are executed.

```
STEP: Creating a listener pod in cluster "amagrawa-c2-4-11", which will wait for a handshake over TCP
W0516 18:52:07.698621 1801003 warnings.go:67] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "tcp-check-listener" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "tcp-check-listener" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "tcp-check-listener" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "tcp-check-listener" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
May 16 18:52:13.048: INFO: Will send traffic to IP: 10.132.4.114
STEP: Creating a connector pod in cluster "amagrawa-c1-411", which will attempt the specific UUID handshake over TCP
W0516 18:52:13.224663 1801003 warnings.go:67] would violate PodSecurity "restricted:latest": host namespaces (hostNetwork=true), runAsNonRoot != true (pod or container "tcp-check-connector" must set securityContext.runAsNonRoot=true)
```

**Comment by nyechiel** [comment]
@dfarrell07 this seems like a good candidate for you to look at with support from @skitt.

**Comment by dfarrell07** [comment]
I was trying to understand this by first focusing on the `query-iface-list` container's errors:

```
W0516 16:30:50.377740   38759 warnings.go:67] would violate PodSecurity "restricted:latest": non-default capabilities (container "query-iface-list" must not include "NET_ADMIN", "NET_RAW" in securityContext.capabilities.add), host namespaces (hostNetwork=true), allowPrivilegeEscalation != false (container "query-iface-list" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "query-iface-list" must set securityContext.capabilities.drop=["ALL"]; container "query-iface-list" must not include "NET_ADMIN", "NET_RAW" in securityContext.capabilities.add), runAsNonRoot != true (pod or container "query-iface-list" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "query-iface-list" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

I thought we wanted to tweak the SecurityContext we create with that pod to add the required permissions, but digging I see we're already setting

> scheduling := pods.Scheduling{ScheduleOn: pods.GatewayNode, Networking: pods.HostNetworking}

https://github.com/submariner-io/subctl/blob/devel/pkg/diagnose/kubeproxy.go#L38

Which I thought would interact with this generic pod scheduling logic to set (some of) the permissions that the errors notes are missing.

```
  if np.Config.Scheduling.Networking == HostNetworking {
    networkPod.Spec.Containers[0].SecurityContext = &v1.SecurityContext{
      Capabilities: &v1.Capabilities{
        Add:  []v1.Capability{"NET_ADMIN", "NET_RAW"},
        Drop: []v1.Capability{"all"},
      },
    }
```

https://github.com/submariner-io/subctl/blob/devel/internal/pods/schedule.go#L138

So it seems like I'm misunderstanding something. Any tips @skitt?

**Comment by sridhargaddam** [comment]
I think the reason we are seeing warning is because of the `PodSecurity` Admission controller which is introduced in K8s 1.23 as described [here](https://kubernetes.io/docs/concepts/security/pod-security-admission/).

I checked an OCP 4.11 deployment for the list of admission controllers that are enabled and see that `PodSecurity` is enabled. From a quick read on how to fix the warning, the documentation says that we can label the namespaces to control the behaviour of podSecurity in the namespace (Ref: https://kubernetes.io/docs/concepts/security/pod-security-admission/#pod-security-admission-labels-for-namespaces). We have to explore if there are any other ways to disable this warning, but atleast labelling the namespaces seem to fix the warning (PSB).

Without any changes, when I run `subctl diagnose kube-proxy-mode ...` command, it displays the warning message.

```
[sgaddam@localhost 30th]$ subctl diagnose kube-proxy-mode --namespace submariner-operator --kubeconfig ./red-cluster-kubeconfig 
Cluster "vthapar-red"
⠈⠑ Checking Submariner support for the kube-proxy mode W0530 23:27:23.913379 3632155 warnings.go:67] would violate PodSecurity "restricted:latest": non-default capabilities (container "query-iface-list" must not include "NET_ADMIN", "NET_RAW" in securityContext.capabilities.add), host namespaces (hostNetwork=true), allowPrivilegeEscalation != false (container "query-iface-list" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "query-iface-list" must set securityContext.capabilities.drop=["ALL"]; container "query-iface-list" must not include "NET_ADMIN", "NET_RAW" in securityContext.capabilities.add), runAsNonRoot != true (pod or container "query-iface-list" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "query-iface-list" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
 ✓ Checking Submariner support for the kube-proxy mode 
 ✓ The kube-proxy mode is supported
```

Lets apply privileged label on the submariner-operator namespace.

```
kubectl label namespace submariner-operator pod-security.kubernetes.io/warn=privileged
```

Now re-run the `subctl diagnose kube-proxy-mode ...` onceagain.

```
[sgaddam@localhost 30th]$ subctl diagnose kube-proxy-mode --namespace submariner-operator --kubeconfig ./red-cluster-kubeconfig 
Cluster "vthapar-red"
 ✓ Checking Submariner support for the kube-proxy mode 
 ✓ The kube-proxy mode is supported
```

**Comment by skitt** [comment]
Right, adding the `privileged` label is the correct fix; see https://lists.corp.redhat.com/archives/aos-devel/2022-May/000798.html for details, and https://github.com/openshift/cluster-kube-apiserver-operator/pull/1234/files for an example.

**Comment by sridhargaddam** [comment]
Thanks for confirming @skitt. 

So, AFAICT we would need the following changes to fix the warning.
1. Label the `submariner-operator` namespace as part of its creation in submariner-operator
2. Submariner as part of e2e tests would create random namespaces and schedules the listener/client pods. The namespaces should be labelled accordingly.
3. Modify `subctl diagnose` to schedule various pods in `submariner-operator` namespace by default, while retaining the existing option where we allow users to override the namespace if required.

Note: I don't think we would require any changes to `subctl benchmark`, but we can validate it once to be sure.

**Comment by nyechiel** [comment]
Thanks for the detailed analysis Sridhar. @dfarrell07 can you please prioritize this work? Let's get it done for 0.13

**Comment by dfarrell07** [comment]
I tried https://github.com/submariner-io/submariner-operator/commit/257083bbcb7f5ce8cdd44f90b3e86a77ed607118:

```
--- a/config/manager/manager.yaml
+++ b/config/manager/manager.yaml
@@ -4,6 +4,9 @@ kind: Namespace
 metadata:
   labels:
     control-plane: submariner-operator
+    pod-security.kubernetes.io/enforce: privileged
+    pod-security.kubernetes.io/audit: privileged
+    pod-security.kubernetes.io/warn: privilege
```

But testing locally that didn't seem to work:

```
[~/go/src/submariner-io/submariner-operator]$ kubectl get namespace submariner-operator -o yaml
apiVersion: v1
kind: Namespace
metadata:    
  creationTimestamp: "2022-06-08T19:01:29Z"
  labels:
    kubernetes.io/metadata.name: submariner-operator
  name: submariner-operator
  resourceVersion: "901"
  uid: 078ad836-9373-4092-95fc-b4c94486e6c8
spec:
  finalizers:
  - kubernetes 
status:
  phase: Active
```

**Comment by skitt** [comment]
That file isn’t used by `subctl`; the namespace is created by https://github.com/submariner-io/subctl/blob/4a0035638495487418ebcedf62c5d58db9b5c70f/pkg/operator/ensure.go#L42 using https://github.com/submariner-io/subctl/blob/b47cf7f3b53d04c9a93ce69001c12e598c8620e3/pkg/namespace/ensure.go#L32 (whose documentation is wrong). The latter needs to be extended to support labels, and the former needs to pass in the appropriate labels — better yet (to handle upgrades), the labels should be added if necessary to whatever namespace ends up being used (new or old).

**Comment by dfarrell07** [comment]
Thanks @skitt, it's great to re-discover this stuff.

I'm now trying https://github.com/submariner-io/subctl/commit/7e88ce7fe977e676702c9181ee446064626eb0b4, which I think covers the "extend labels/pass labels" parts but not yet the upgrade idea.

But I'm still not seeing the labels in my local `make deploy`.

```
[~/go/src/submariner-io/subctl]$ kubectl get namespace submariner-operator -o yaml                                                                                                                [ns_privg_labels]
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2022-06-09T23:17:57Z"
  labels:
    kubernetes.io/metadata.name: submariner-operator
  name: submariner-operator
  resourceVersion: "3266"
  uid: 0264bfab-cc17-4b98-b886-a6254ec12b67
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```

:thinking:

**Comment by dfarrell07** [comment]
I added some (currently-failing) tests for this: https://github.com/dfarrell07/subctl/pull/2/commits/a2384738a39caebe07f54fc392ebfe7cef6a79ef

And booked an office hours slot with Stephen to discuss more tomorrow.

**Comment by dfarrell07** [comment]
First issue was that we were not testing the version of subctl we were building. Stephen sent a fix here: https://github.com/submariner-io/subctl/pull/97

**Comment by dfarrell07** [comment]
I have this passing for greenfield: https://github.com/dfarrell07/subctl/pull/2

Still need to figure out how to write a mutate function to pass to `admiral/pkg/util.CreateOrUpdate` to add the labels if the namespace already exists to get upgrades working.

**Comment by skitt** [comment]
It might be easier to use `sigs.k8s.io/controller-runtime/pkg/controller/controllerutil.CreateOrUpdate()`, see https://github.com/submariner-io/submariner-operator/blob/02579fcd094df9bbbf141d2b77c19d9558738e2a/controllers/helpers/helpers.go#L58

**Comment by dfarrell07** [comment]
I found the Admiral CreateOrUpdate to be easier to work with.

This PR in Admiral was necessary to add a resource.ForNamespaces function: https://github.com/submariner-io/admiral/pull/368

The main PR is ready for review and passing all tests, including upgrades: https://github.com/submariner-io/subctl/pull/105

This PR shows that the tests correctly fail without the fix: https://github.com/dfarrell07/subctl/pull/4

**Comment by sridhargaddam** [comment]
> 1. Label the `submariner-operator` namespace as part of its creation in submariner-operator

I verified this in 0.13.0-rc0 image and see that namespace has the required labels.

> 2. Submariner as part of e2e tests would create random namespaces and schedules the listener/client pods. The namespaces should be labelled accordingly.
> 3. Modify `subctl diagnose` to schedule various pods in `submariner-operator` namespace by default, while retaining the existing option where we allow users to override the namespace if required.

However, 2 and 3 above are still showing warnings with 0.13.0-rc0 image. Shall we report separate issues for them or use the same issue?

**Comment by nyechiel** [comment]
> > 1. Label the `submariner-operator` namespace as part of its creation in submariner-operator
> 
> I verified this in 0.13.0-rc0 image and see that namespace has the required labels.
> 
> > 2. Submariner as part of e2e tests would create random namespaces and schedules the listener/client pods. The namespaces should be labelled accordingly.
> > 3. Modify `subctl diagnose` to schedule various pods in `submariner-operator` namespace by default, while retaining the existing option where we allow users to override the namespace if required.
> 
> However, 2 and 3 above are still showing warnings with 0.13.0-rc0 image. Shall we report separate issues for them or use the same issue?

Yes, can you please report individual issues and make sure they are being added to the 0.13 board? we need to review and decide if we should get them into rc1.

**Comment by sridhargaddam** [comment]
The following issues are reported to track 2 and 3 above:
https://github.com/submariner-io/subctl/issues/119
https://github.com/submariner-io/subctl/issues/118
