### ISSUE TITLE
Add a three-context variant for subctl verify

### ISSUE THREAD

**Issue by skitt** [submariner-io/subctl#276]
**What would you like to be added**:

`subctl verify` should support three contexts.

**Why is this needed**:

Some Lighthouse tests only run if three contexts are available; it would be good to be able to run them using `subctl verify`.

**Comment by skitt** [comment]
For QE purposes it would also be useful to run (optionally?) all two-context tests over all pairs of contexts, when more than two contexts are available.

**Comment by dfarrell07** [comment]
Note that in CI we do run these tests as we run E2E directly, this is just missing for `subctl verify`.
