### ISSUE TITLE
subctl uninstall doesn’t remove the Globalnet ConfigMap

### ISSUE THREAD

**Issue by skitt** [submariner-io/subctl#30]
I installed Submariner with Globalnet, then uninstalled it, and re-installed it without requesting Globalnet. However, joining the clusters showed that Globalnet was enabled:

> * broker-info.subm says broker is at: https://api.skitt-hub.subm.red-chesterfield.com:6443
> * There are 1 labeled nodes in the cluster:
>   - ip-10-0-2-2.us-east-2.compute.internal
> ⠈⠑ Discovering network details         Network plugin:  OpenShiftSDN
>         Service CIDRs:   [172.30.0.0/16]
>         Cluster CIDRs:   [10.128.0.0/14]
>  ✓ Discovering network details
>  ✓ Retrieving Globalnet information from the Broker 
>  ✓ Validating Globalnet configuration
>  ✓ Assigning Globalnet IPs
>  ✓ Using pre-configured global CIDR 242.0.0.0/16
>  ✓ Deploying the Submariner operator 
>  ✓ Created operator CRDs
>  ✓ Created operator namespace: submariner-operator
>  ✓ Created operator service account and role
>  ✓ Created lighthouse service account and role
>  ✓ Created Lighthouse service accounts and roles
>  ✓ Deployed the operator successfully
>  ✓ Creating SA for cluster 
>  ✓ Deploying Submariner 
>  ✓ Submariner is up and running

`subctl uninstall` on the broker should remove the broker’s Globalnet ConfigMap.

Note that even if one wouldn’t expect to disable Globalnet after uninstalling Submariner, the ConfigMap preserves the IP allocations which might not be appropriate:

```
{
    "apiVersion": "v1",
    "data": {
        "clusterinfo": "[\n\t{\n\t\t\"cluster_id\": \"skitt-1\",\n\t\t\"global_cidr\": [\n\t\t\t\"242.0.0.0/16\"\n\t\t]\n\t},\n\t{\n\t\t\"cluster_id\": \"skitt-2\",\n\t\t\"global_cidr\": [\n\t\t\t\"242.1.0.0/16\"\n\t\t]\n\t}\n]",
        "globalnetCidrRange": "\"242.0.0.0/8\"",
        "globalnetClusterSize": "65536",
        "globalnetEnabled": "true"
    },
    "kind": "ConfigMap",
    "metadata": {
        "creationTimestamp": "2022-03-04T12:28:58Z",
        "labels": {
            "component": "submariner-globalnet"
        },
        "name": "submariner-globalnet-info",
        "namespace": "submariner-k8s-broker",
        "resourceVersion": "56791",
        "uid": "9a0002d7-6a87-4d30-8b8a-94df877b4911"
    }
}
```

**Comment by sridhargaddam** [comment]
When the cluster is used as Broker as well as managedCluster, the `subctl uninstall ...` command [deletes the BrokerNamespace](https://github.com/submariner-io/submariner-operator/blob/a1dbdeebe3c7f39a14784d353c81569307dc740f/pkg/uninstall/all.go#L74) which in-turn should delete the globalnet ConfigMap. 

Are you seeing this problem on **Broker only** Cluster or even on a cluster which is both Broker+ManagedCluster?

**Comment by skitt** [comment]
> When the cluster is used as Broker as well as managedCluster, the `subctl uninstall ...` command [deletes the BrokerNamespace](https://github.com/submariner-io/submariner-operator/blob/a1dbdeebe3c7f39a14784d353c81569307dc740f/pkg/uninstall/all.go#L74) which in-turn should delete the globalnet ConfigMap.
> 
> Are you seeing this problem on **Broker only** Cluster or even on a cluster which is both Broker+ManagedCluster?

This was on a broker-only cluster, ACM-style.

**Comment by tpantelis** [comment]
We obtain the broker namespace from the `Submariner` (or `ServiceDiscovery`) CR. The problem is that on a broker-only cluster the `Submariner` CR doesn't exist. In that case we could allow the user to pass the broker namespace (or prompt) and, otherwise, assume the default namespace.

**Comment by nyechiel** [comment]
@tpantelis are you planning to work on it this week?

**Comment by tpantelis** [comment]
> @tpantelis are you planning to work on it this week?

yes
