### ISSUE TITLE
Move subctl releases away from a moving tag on the HEAD

### ISSUE THREAD

**Issue by arewm** [submariner-io/subctl#32]
**What would you like to be added**:

The `subctl` releases should not be created based on tags. The only tags created should be valid SemVer used for tracking specific versions.

**Why is this needed**:
Not only is the `subctl` tag not valid SemVer, but it is also not static. If it is only needed for releases, can we move releases off of the tag so that there isn't additional confusion potentially introduced? This would also benefit automation working off of tags by introducing a SemVer standard.

**Comment by skitt** [comment]
This would also avoid requiring `git fetch --tags --force` in clones.

**Comment by mkolesnik** [comment]
Subctl is released on https://github.com/submariner-io/releases/releases, any releases in this project are just for testing purposes and thus use "floating tags" but never consumed by users, see https://get.submariner.io/

Any release made here should be ignored if your'e not a developer, and we don't publish any binaries for tags on this repo

**Comment by gurnben** [comment]
We have some automation that picks up the latest `subctl` release that's in semver format, but it assumes that the semver tag will be the _only_ tag on a commit.  This automation falls apart when both the non-semver floating tag and the semver release tag point to the same commit, but only when the non-semver floating tag is the newest tag on that commit, so it appears first in the list of `git describe --tags <commit-sha>` on that given commit.  

That being said, there's an easy workaround - we'll update our automation to pick up and filter the list of tags from `git describe` on the same semver rules.  Its an extra step but probably a good one to have in the process nonetheless!  

From my perspective - I think this isn't an issue for me (and likely @arewm who is using the same automation) moving forward!  

Unless @skitt or @arewm have any concerns we can probably close this one as "not implementing".

**Comment by skitt** [comment]
Heh, I thought about suggesting that (`git describe --tags --match 'v*'`) yesterday! If CI is fixed to no longer need this, that’s a much better solution across the board. I’ll let @arewm close this if he agrees it’s no longer needed.

**Comment by arewm** [comment]
@gurnben said that the solution I implemented worked on a rerun. Closing.
