### ISSUE TITLE
`subctl diagnose firewall inter-cluster` references a hard-coded image: `quay.io/submariner/nettest:devel`

### ISSUE THREAD

**Issue by cgruver** [submariner-io/subctl#34]
The image used for testing the network appears to be hard coded:

`quay.io/submariner/nettest:devel`

I have Submariner `v0.12.0` installed on set of 3 OKD 4.10 clusters.  These clusters are disconnected from the internet.

I am able to successfully install and configure Submariner using the `--repository ${PRIVATE_REGISTRY}/submariner --version ${SUBMARINER_VER}` options.

These options do not appear to be supported in the diagnostic tools.  Thus, the diagnostics fail because the image cannot be pulled.

The relevant code appears to be here:

```bash
./submariner-operator/internal/pods/schedule.go
```

```go
func (np *Scheduled) schedule() error {
	if np.Config.Scheduling.ScheduleOn == CustomNode && np.Config.Scheduling.NodeName == "" {
		return fmt.Errorf("CustomNode is specified for scheduling, but nodeName is missing")
	}

	networkPod := v1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			GenerateName: np.Config.Name,
			Labels: map[string]string{
				"app": np.Config.Name,
			},
		},
		Spec: v1.PodSpec{
			RestartPolicy: v1.RestartPolicyNever,
			HostNetwork:   bool(np.Config.Scheduling.Networking),
			Containers: []v1.Container{
				{
					Name:    np.Config.Name,
					Image:   "quay.io/submariner/nettest:devel",
					Command: []string{"sh", "-c", "$(COMMAND) >/dev/termination-log 2>&1 || exit 0"},
					Env: []v1.EnvVar{
						{Name: "COMMAND", Value: np.Config.Command},
					},
				},
			},
			Tolerations: []v1.Toleration{{Operator: v1.TolerationOpExists}},
		},
	}
```

**Comment by dfarrell07** [comment]
"So we need this code to honor the `--version` and `--repo` flags" - @skitt 

Discussed on the PR/Issue scrub, seems valid thanks for reporting. :+1:
