### ISSUE TITLE
System tests should use a function

### ISSUE THREAD

**Issue by skitt** [submariner-io/subctl#345]
Many system tests use a pattern like

    … | tee /dev/stderr | (sponge ||:) | grep -q …

(or `-qv` in the last step).

This should be turned into a function to avoid all the repetition and to simplify changes such as #344.

**Comment by dfarrell07** [comment]
This seems like a good idea, in particular if we're extending or changing the system tests, but I don't think we have any current plans to do so. We should remember this and revisit it if we change the system tests.
