### ISSUE TITLE
`subctl verify` is dumping client API warnings throughout the run

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/subctl#38]
**What happened**:
While running `subctl verify` these messages pop up:
```
W0314 12:10:17.164101  112887 warnings.go:67] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
W0314 12:10:22.324752  112887 warnings.go:67] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
W0314 12:10:27.326988  112887 warnings.go:67] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
```

**What you expected to happen**:
We should print them in aggregate, similar to submariner-io/submariner-operator#1910

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by dfarrell07** [comment]
While this particular warning will be fixed by https://github.com/submariner-io/subctl/issues/45, it seems the idea here is to group warnings better, so not closing as duplicate. - PR scrub

**Comment by dfarrell07** [comment]
> it seems the idea here is to group warnings better

Maybe this should be a different issue and we can close this one, which is actually done?

**Comment by dfarrell07** [comment]
This shouldn't happen in newer versions. Closing for now, if anyone hits this again or something similar we can open a more relevant issue to fix.
