### ISSUE TITLE
subctl join discovered wrong network details

### ISSUE THREAD

**Issue by lazywhite** [submariner-io/subctl#444]
**What happened**:
followed the official k3s [quick start guid ](https://submariner.io/getting-started/quickstart/k3s/)
```subctl join``` show wrong Discovering network detail, and joined clusterset with  wrong configuration
```
root@kvm3:~# subctl join --context cluster2 --clusterid cluster2 --natt=false broker-info.subm 
 ✓ broker-info.subm indicates broker is at https://192.168.122.57:6443
 ✓ Discovering network details
        Network plugin:  generic
        Service CIDRs:   [12.43.0.0/16]
        Cluster CIDRs:   [12.42.0.0/24]

```

my environment
```
cluster1 has --cluster-cidr 11.42.0.0/16 --service-cidr 11.43.0.0/16
cluster2 has --cluster-cidr 12.42.0.0/16 --service-cidr 12.43.0.0/16
deploy broker on cluster1

cluster1 has one node 192.168.122.57/24
cluster2 has two nodes 192.168.122.58/24 192.168.122.52/24
```
I think Cluster CIDRs should be either 12.42.0.0/16 (global) or [12.42.0.0/24,12.42.1.0/24] (pod cidr of two nodes)

**What you expected to happen**:
subctl join should discover cluster networks information correctly
**How to reproduce it (as minimally and precisely as possible)**:
every time when I try to join a cluster 
subctl join --context cluster2 --clusterid cluster2 --natt=false broker-info.subm 
**Anything else we need to know?**:
```

subctl version: v0.14.0 and v0.14.1
```

**Comment by lazywhite** [comment]
solved by manually specify cluster-cidr 
```subctl join --context cluster2 --clusterid cluster2 --clustercidr 12.42.0.0/16 --natt=false broker-info.subm ```

**Comment by lazywhite** [comment]
I think the problem is why subctl discovered wrong network information and it should be fixed

**Comment by skitt** [comment]
We’ve recently improved network detection for a number of plugins; @lazywhite would you mind testing again with 0.16.0?
