### ISSUE TITLE
subctl diagnose: support --kubecontexts

### ISSUE THREAD

**Issue by skitt** [submariner-io/subctl#49]
In a similar fashion to `subctl verify`, it would be nice if `subctl diagnose` supported `--kubecontexts` where relevant, _e.g._ on `tunnels`.

**Comment by skitt** [comment]
This is still relevant.

**Comment by ghost** [comment]
The documentation suggest the '--kubecontext' on for instance the show and export (see https://submariner.io/operations/deployment/subctl/) but the standard subctl install, or the dev package, don't seem to understand that option.
Is this scheduled for a next build?

(The go build complains on missing deps, so I could not try that).

**Comment by nyechiel** [comment]
@skitt I think this is done now?

**Comment by skitt** [comment]
> @skitt I think this is done now?

Not yet; it’s easy now, but it’s not done.

**Comment by skitt** [comment]
This is done, not quite as `--kubecontexts`, but with explicit `--context` flags.
