### ISSUE TITLE
subctl verify with a single context should be more explicit

### ISSUE THREAD

**Issue by skitt** [submariner-io/subctl#513]
**What happened**:

I ran

```
subctl verify --context admin-1
```

(_i.e._ with a single context).

This failed with

```
? You have specified disruptive verifications (gateway-failover). Are you sure you want to run them? No
Performing the following verifications: connectivity, service-discovery
 ✗ Two kubecontexts must be specified

subctl version: v0.15.0-m2
```

**What you expected to happen**:

I had forgotten that this required two contexts, so I expected it to run, but that was wrong (and not the focus of this issue).

However, the error message should explain how to specify the two contexts.

**How to reproduce it (as minimally and precisely as possible)**:

See above.

**Comment by dfarrell07** [comment]
@tpantelis pointed out that we likely should do the two-contexts check before prompting as well, to fail as fast as possible.
