### ISSUE TITLE
`subctl cloud-prepare` finshes with spinner still going

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/subctl#519]
Running cloud prepare and seeing this behavior:
```bash
[root@36efcb63aedb shipyard]# subctl cloud prepare azure --ocp-metadata output/ocp-cluster1/ --auth-file ~/.azure/osServicePrincipal.json
 ✓ Preparing Azure cloud for Submariner deployment 
 ✓ Obtained infra ID "mkolesni-testday-clus-fgz8k" and region "eastus" from OCP metadata file "output/ocp-cluster1/"
 ✓ Retrieving Azure credentials from your Azure authorization file "/root/.azure/osServicePrincipal.json"
 ✓ Initializing Azure connectivity 
 ✓ Deploying gateway node 
 ✓ Current gateways match the required number of gateways
⠈⠱ Opening internal ports for intra-cluster communications on Azure [root@36efcb63aedb shipyard]# 
```

As can be seen, the process just exits unexpectedly without any additional output.

I've used OCP 4.12 if that makes any difference.

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by mkolesnik** [comment]
This was also observed with `subctl` versions 0.14.1 and 0.13.3, they all depict the same behavior.

**Comment by nyechiel** [comment]
Might be related to https://github.com/submariner-io/subctl/issues/517, although it looks like this issue is not specific to 0.15

**Comment by mkolesnik** [comment]
> Might be related to submariner-io/subctl#517, although it looks like this issue is not specific to 0.15

I don't think it's related as the same exact behavior also happens on older versions where we didn't have metrics proxy (e.g. before the port was removed)

**Comment by mkolesnik** [comment]
After further investigation it seems to be a problem with the spinner, eg the command itself did finish successfully, I will work on a fix
