### ISSUE TITLE
subctl operations which deploy images should allow them to be overridden

### ISSUE THREAD

**Issue by skitt** [submariner-io/subctl#524]
**What would you like to be added**:

An option to override images used by operations such as `verify`, `benchmark` etc. similar to `--image-override` with `subctl join`.

**Why is this needed**:

Images can be overridden with `subctl join`, but this sets up overrides through the `Submariner` CR. In some contexts this isn’t sufficient (_e.g._ the images aren’t appropriate when running `subctl` after the deployment, or the user needs to use different images than those specified by the `Submariner` CR) and further overrides need to be specified for operations such as `subctl verify`.

**Comment by nyechiel** [comment]
Needs a backport to `release-0.14`
