### ISSUE TITLE
The No "Apply suggestions from code review" Commits GHA needs to be updated

### ISSUE THREAD

**Issue by skitt** [submariner-io/subctl#537]
This GHA will soon run into problems because of GHA feature removals:

* Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: tim-actions/get-pr-commits@c64db31d359214d244884dd68f971a110b29ab83, tim-actions/commit-message-checker-with-regex@d6d9770051dd6460679d1cab1dcaa8cffc5c2bbd. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
* The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Depends on https://github.com/tim-actions/get-pr-commits/issues/8
Depends on https://github.com/tim-actions/commit-message-checker-with-regex/issues/8

**Comment by dfarrell07** [comment]
I was thinking about sending an update, but there are already PRs proposed but not merged.

Depends on https://github.com/tim-actions/get-pr-commits/pull/11
Depends on https://github.com/tim-actions/commit-message-checker-with-regex/pull/12

**Comment by dfarrell07** [comment]
One of two merged. :crossed_fingers:

**Comment by dfarrell07** [comment]
Both are merged :heavy_check_mark:

**Comment by dfarrell07** [comment]
Not sure if we should wait on releases (might not happen, or at least be slow) or bump manually.

**Comment by skitt** [comment]
> Not sure if we should wait on releases (might not happen, or at least be slow) or bump manually.

Let’s bump manually.

**Comment by dfarrell07** [comment]
All the backports for this are proposed.

**Comment by dfarrell07** [comment]
All the backports are merged, this is done. :heavy_check_mark:
