### ISSUE TITLE
subctl imageoverride is missing the name.MetricsProxyComponent constant

### ISSUE THREAD

**Issue by zhaoyujingpy** [submariner-io/subctl#569]
**What happened**:When using the imageoverride parameter to join the cluster, name verification is required. The verified name is missing: names.MetricsProxyComponent, and an error is reported when joining the cluster:invalid override component  provided

**What you expected to happen**:
Use the submariner-metrics-proxy parameter to override the submariner-mertics pod image name when joining the group

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:Just add names.MetricsProxyComponent to validOverrides to solve the problem

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by dfarrell07** [comment]
@zhaoyujingpy Thanks! Since you've basically identified exactly what should be done, do you want to write the PR? We always love to have new contributors!
