### ISSUE TITLE
--image-override doesn’t work everywhere

### ISSUE THREAD

**Issue by skitt** [submariner-io/subctl#597]
A number of `subctl` commands support an `--image-override` flag, but it doesn’t actually work everywhere; we need to test all the variants and identify gaps.

To test the flag, specify an invalid `nettest` image using `--image-override=submariner-nettest=…` and check that the command fails.

- [x] [Include image-override as a firewall subcmd](https://github.com/submariner-io/subctl/pull/598)
- [x] [Support image-override in diagnose all command](https://github.com/submariner-io/subctl/pull/602)

**Comment by sridhargaddam** [comment]
I see that we already have validations in the code to return appropriate error message when an invalid image override name is supplied. This is cool.

```
[sgaddam@localhost 9th]$ subctl diagnose kube-proxy-mode --image-override=abc=quay.io/testing
Cluster "hub-cluster"
 ✗ Checking Submariner support for the kube-proxy mode
 ✗ Error determining repository information: invalid override component abc provided. Please choose from ["submariner-operator" "submariner-gateway" "submariner-routeagent" "submariner-globalnet" "submariner-networkplugin-syncer" "submariner-lighthouse-agent" "submariner-lighthouse-coredns" "submariner-nettest"]

subctl version: devel
```
