### ISSUE TITLE
Subctl gather should prompt the list of contexts and allow users to pick one (or all)

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/subctl#729]
**What would you like to be added**:
Currently, when the KUBECONFIG file includes multiple contexts, and user executes `subctl gather ...` command, the command is executed with all the contexts and the `summary.html` includes the information for all the contexts. While this is okay when the contexts point to different clusters, but we have seen many instances where the KUBECONFIG includes multiple contexts for the same cluster and user is not even aware of this. The side effect of this is that it take a good amount of time for the command to complete particularly in large clusters and also makes it difficult to troubleshoot the issue looking at the summary.html as it has so many entries.

Proposal:
When the command subctl gather ... is run, present the user with a list of contexts and give them the option to choose the context (either a single context or all) on which the command should be executed.

**Comment by tpantelis** [comment]
@sridhargaddam Would the problem be solved if we de-duplicate the clusters, ie if multiple contexts point to the same cluster by name then we pick one of contexts and ignore the rest?

**Comment by sridhargaddam** [comment]
> @sridhargaddam Would the problem be solved if we de-duplicate the clusters, ie if multiple contexts point to the same cluster by name then we pick one of contexts and ignore the rest?

Even when multiple contexts point to the same server, the user-account associated with each context can have different privileges. It would be hard to automatically figure out which context has admin privileges. But, we can try running a command that usually requires admin privileges against all contexts (belonging to the same cluster) and see if it succeeds, and use the same for capturing the logs (i.e., gather)

**Comment by tpantelis** [comment]
> Even when multiple contexts point to the same server, the user-account associated with each context can have different privileges. It would be hard to automatically figure out which context has admin privileges. But, we can try running a command that usually requires admin privileges against all contexts (belonging to the same cluster) and see if it succeeds, and use the same for capturing the logs (i.e., gather)

So what command would we run? 

How about we de-duplicate by cluster and, if there's multiple contexts for a cluster, we prompt the user to pick the context for that cluster? 

The downside with prompting is if the shell is non-interactive. For verify where we prompt for disruptive tests, we print a message and continue running with non-disruptive tests. In this case, we can print a warning and skip the cluster or just pick one of the contexts. If it fails the user can re-run with specific context(s).

**Comment by tpantelis** [comment]
As an alternative to prompting we could bias towards using the cluster's context whose associated user is also associated to another cluster's context. So we first iterate all the contexts and compile the count of contexts for each user. Then for a cluster with multiple contexts we select the one with highest associated context count. Presumably an admin should be associated with the most contexts. If there's only one cluster then just pick the first - if it fails the user can re-run with a specific context. We can log a warning re: multiple contexts and the one we selected.

Here's same output:

```
Cluster "cluster1"
...

 ⚠ Found multiple kube contexts for cluster "cluster2":
    cluster2-admin
    cluster2-other2
    cluster2-other1
  Context "cluster2-admin" was automatically selected however if the associated user account does not have sufficient privilages, please re-run the command with the suitable context.

Cluster "cluster2"
...
```
