### ISSUE TITLE
On OpenShift, none of the Globalnet metrics show up

### ISSUE THREAD

**Issue by skitt** [submariner-io/subctl#73]
I set up three clusters (one broker, two joined clusters) running OpenShift, and installed Submariner with Globalnet. This can be confirmed by looking at the Cluster objects:

```yaml
apiVersion: submariner.io/v1
kind: Cluster
metadata:
[...]
  name: skitt-1
  namespace: submariner-k8s-broker
  resourceVersion: '57012'
  uid: a84b25f2-35b7-4a84-a981-6ba889d9373a
spec:
  cluster_cidr:
    - 10.128.0.0/14
  cluster_id: skitt-1
  color_codes:
    - blue
  global_cidr:
    - 242.0.0.0/16
  service_cidr:
    - 172.30.0.0/16
```

However, none of the Globalnet metrics show up in OpenShift monitoring:

![Screenshot from 2022-03-04 14-22-06](https://user-images.githubusercontent.com/2128935/156770942-7a14f312-1ddf-4707-a984-74ea870beca4.png)

**Comment by nyechiel** [comment]
Not going to be fixed for 0.12.0. I have opened https://github.com/submariner-io/submariner-website/issues/703 to ensure we document this as a known issue for now.

**Comment by sridhargaddam** [comment]
Globalnet pod exposes metrics on [TCP/8081](https://github.com/submariner-io/submariner/blob/ba449531a369f27541a3d9fcd197e77868c9aac7/pkg/globalnet/main.go#L144) and this port is not configured as part of cloud_prepare, hence we are  unable to see the Globalnet metrics. When I manually opened the port, I am able to see the metrics supported from Globalnet. The fix needs to be implemented in cloud-prepare.


![Screenshot from 2022-03-09 13-52-30](https://user-images.githubusercontent.com/6574656/157402501-ad565825-f1da-406c-a70a-3010fc89b7ec.png)

**Comment by sridhargaddam** [comment]
The necessary change has to be done in "subctl cloud prepare aws/gcp/rhos/xxx" utility to allow reading the additional port. This can be done either by modifying the current `--metrics-port` flag to allow multiple values (care has to be taken about backward compatibility issues) or by introducing a new metrics flag for Globalnet metrics.

**Comment by sridhargaddam** [comment]
Along with this, we also need changes in `subctl diagnose ...` to verify if the Globalnet metrics port is configured.

**Comment by sridhargaddam** [comment]
> Along with this, we also need changes in `subctl diagnose ...` to verify if the Globalnet metrics port is configured.

Reported a separate issue to track this - submariner-io/subctl#42

**Comment by mkolesnik** [comment]
Should probably change flag in subctl to receive multiple ports instead of adding a new flag, default should remain 8080 unless we expect most of the deployments to use globalnet in whyich case we can add it to default in the future

**Comment by dfarrell07** [comment]
@skitt will check if this is still an issue. - PR scrub

**Comment by skitt** [comment]
This hasn’t been fixed.

**Comment by nyechiel** [comment]
@maayanf24 I thought you are working on it?

**Comment by maayanf24** [comment]
> @maayanf24 I thought you are working on it?

I started to look into this, I have some implementation questions:
best option is to make flag `--metrics-port` accept multiple values.
should calling `subctl cloud prepare aws  --metrics-port 8081 ...` means that we add internal the default port? (8080)
or user must explicitly specify all ports if using the flag? `subctl cloud prepare aws  --metrics-port 8080 --metrics-port 8081...`

**Comment by skitt** [comment]
I would make the default `8080,8081` so that things “just work” in the default case.
