### ISSUE TITLE
Subctl gather should read the Submariner version from status field instead of spec

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/subctl#746]
**What happened**:

Currently when `subctl gather ...` is executed against a cluster, it tries to get the Submariner version from the `submariners.spec.version` field. However, it should read this info from `submariners.status.version` as there is some discrepancy observed when a different version of subctl is used which does not match with the installed version.

**Comment by yboaron** [comment]
@sridhargaddam , did you mean to use (*(info.Submariner.Status.Gateways))[0].Version ?  something like [1] .

Because I couldn't find Version field under  Submariner.Status.

Also can you elaborate on why reading version info from submariners.status instead of submariner.spec will fix this issue  

[1] 
https://github.com/submariner-io/subctl/pull/747

**Comment by tpantelis** [comment]
> @sridhargaddam , did you mean to use (*(info.Submariner.Status.Gateways))[0].Version ? something like [1] .

This is problematic if there's no Gateways or if connectivity is not installed. However `spec.version` is guaranteed to be populated when read from the API server via [this code](https://github.com/submariner-io/submariner-operator/blob/809274cc82b48ea3e12ae838a089c62ab5642a63/api/v1alpha1/submariner_types.go#L354).

> Also can you elaborate on why reading version info from submariners.status instead of submariner.spec will fix this issue

The problem that was observed was b/c `spec.version` isn't populated when installed via ACM so `subctl gather` et al will default to the [version](https://github.com/submariner-io/submariner-operator/blob/809274cc82b48ea3e12ae838a089c62ab5642a63/api/v1alpha1/versions.go#L25) baked into the `subctl` binary. I think the most ideal solution is to have the add-on set `spec.version` when creating the `Submariner` resource.

**Comment by tpantelis** [comment]
> I think the most ideal solution is to have the add-on set `spec.version` when creating the `Submariner` resource.

https://github.com/stolostron/submariner-addon/pull/902

**Comment by dfarrell07** [comment]
We talked about backporting this fix in the addon, not sure if it's needed, let us know what you think @sridhargaddam.

**Comment by sridhargaddam** [comment]
> We talked about backporting this fix in the addon, not sure if it's needed, let us know what you think @sridhargaddam.

As this is not going to affect any functionality, but helps in preventing any confusion that could arise while analysing the logs, I think it would help to backport the PR.

**Comment by tpantelis** [comment]
> As this is not going to affect any functionality, but helps in preventing any confusion that could arise while analysing the logs, I think it would help to backport the PR.

OK. Let's get it reviewed/merged in main 😉

**Comment by tpantelis** [comment]
The consensus is o add the `Subtmaraner.Status.Version` field: https://github.com/submariner-io/submariner-operator/pull/2668.
