### ISSUE TITLE
is there any projects using subctl command as apis to use

### ISSUE THREAD

**Issue by jinglina** [submariner-io/subctl#850]
I want to using subctl as a clinet to `deploy-broker` or `join` `export service` to do multicluster service discovery. Is there any project to provide subctl client like `kubelet` to operator these actions??
if any apis for subctl provided ,please help ,or any suggestions when using `subctl` command in application?

**Comment by dfarrell07** [comment]
I'm not totally sure I understand what you're looking for, but here's a try. Please clarify if it's not what you're looking for.

It should be possible to use some subctl features as a golang library, like `join`. It's separated from the CLI, built as a library. There may be other refactoring we can do to make this easier for other features (let us know). 

https://github.com/submariner-io/subctl/tree/devel/pkg/join
