### ISSUE TITLE
After Helm deployment, `subctl uninstall` fails

### ISSUE THREAD

**Issue by jinglina** [submariner-io/subctl#879]
when using command to uninstall submariner-related components, it shows terminating when deleting namespace **submariner-operator** . I wonder how to avoild this .
```
subctl uninstall
```

**Comment by sridhargaddam** [comment]
@jinglina to understand the issue, we would need some additional info like

1. Output of subctl gather
2. Cloud provider and CNI details

Submariner uses finalizers on certain objects for the cleanup operation to happen properly. When you run the command `subctl uninstall`, it can sometimes take around 2 mins for the operation to complete. Are you saying that it continues to hang even after 2 mins in your setup? If so, please include the following info as well

1. The output of `subctl uninstall ...` command 
2. While the command was running do you see pods scheduled in "submariner-operator" namespace with a suffix of `xxxx-xxx-uninstall-xxx` ?

**Comment by jinglina** [comment]
It always shows in this case when I deploy broker using helm ,and join clusters using ```subctl``` command.I will gather related information later.
And what do you think when deploying broker using helm and join clusters using comamnd ?
Thanks

**Comment by tpantelis** [comment]
> It always shows in this case when I deploy broker using helm ,and join clusters using `subctl` command.I will gather related information later. And what do you think when deploying broker using helm and join clusters using comamnd ?

`subctl join` requires a broker info file created via `subctl deploy-broker` so how is it even possible to only use helm for deploy broker? And why would you want to mix the two, just use one or the other, preferably `subctl` as that is better maintained.

**Comment by jinglina** [comment]
Sorry, I made a mistake. I deploy broker and join clusters using helm,and uninstall using comand.

**Comment by dfarrell07** [comment]
> @jinglina to understand the issue, we would need some additional info like
> 
> 1. Output of subctl gather
> 2. Cloud provider and CNI details
> 
> Submariner uses finalizers on certain objects for the cleanup operation to happen properly. When you run the command `subctl uninstall`, it can sometimes take around 2 mins for the operation to complete. Are you saying that it continues to hang even after 2 mins in your setup? If so, please include the following info as well
> 
> 1. The output of `subctl uninstall ...` command
> 2. While the command was running do you see pods scheduled in "submariner-operator" namespace with a suffix of `xxxx-xxx-uninstall-xxx` ?

@jinglina Reminder about the requests for details here. It might also be helpful to just run `subctl gather` and provide the resulting file. Also dump the Namespace resource - the status should provide details as to why it's in the terminating state. If it's due to a remaining finalizer, try listing the resources to identify which one.

**Comment by dfarrell07** [comment]
Closing for now, feel free to re-open if there's more discussion to be had.
