### ISSUE TITLE
Warnings seen while running subctl join command

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/subctl#880]
**What happened**:

When installing Submariner on an OCP 4.14 nightly build cluster, the following warnings are seen as part of `subctl join ...` command. 

```
⢎⠁ Creating SA for cluster W0814 22:31:47.663076  381769 warnings.go:70] Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
⠈⠁ Creating SA for cluster W0814 22:31:47.960438  381769 warnings.go:70] Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
⠈⠱ Creating SA for cluster W0814 22:31:48.217718  381769 warnings.go:70] Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
⢄⡱ Creating SA for cluster W0814 22:31:48.477673  381769 warnings.go:70] Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
```

**Environment**:
- Install tools: latest subctl devel image.

**Comment by tpantelis** [comment]
This warning seems to be new with K8s 1.27 as it's seen in this [1.27 E2E job](https://github.com/submariner-io/submariner-operator/actions/runs/5827508831/job/16072320662?pr=2759#step:3:1446) but not in 1.26.

This is related to the client token `Secret` associated with `ServiceAccounts`. Prior to 1.24, K8s auto-generated it but that mechanism has changed and is no longer [recommended](https://kubernetes.io/docs/concepts/security/service-accounts/#get-a-token). This is governed by the [LegacyServiceAccountTokenNoAutoGeneration](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-graduated-or-deprecated-features) feature gate which was enabled GA in 1.26 so i'm unclear how this is working for us in 1.26. Perhaps we disabled the feature gate or something.

The `TokenRequest` API approach creates a short-lived token so I'm not sure if this is ideal for our purpose. We can also create a long-lived token by manually creating the associated `Secret` as described [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-long-lived-api-token-for-a-serviceaccount).

**Comment by tpantelis** [comment]
It turns out we already manually create the `Secret` - this was added  by https://github.com/submariner-io/subctl/pull/125/. So now the question is why does K8s issue the warning? How does it even detect if someone is trying to use the legacy behavior? I suspect it's b/c we're setting the `secrets` field in the `ServiceAccount`. This shouldn't be necessary.
