### ISSUE TITLE
helm install is different to subctl deploy-broker

### ISSUE THREAD

**Issue by jinglina** [submariner-io/subctl#882]
When I use command ``` subctl deploy-broker```, the submariner-operator component will run in the broker cluster in submariner-operator namesapce.It works well and the code shows it well.
when using ```helm install submariner-k8s-broker submariner-k8s-broker``` which is in helm release, it just crds related and submariner-operator componnet wont start in broker cluster even I joined another clusters to this broker cluster.
I cannot figure out why is it? As I know, in broker cluster, submariner-operator component is needed here.
any suggestons?

**Comment by dfarrell07** [comment]
Helm doesn't use the Operator currently, see: https://github.com/submariner-io/submariner-charts/issues/134 (we'd love to get that changed, but need contributors to Helm)

Generally, likely it's best not to mix Helm and subctl  - just pick one.
