### ISSUE TITLE
`subctl upgrade` tests fail on `rc0` pre release

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/subctl#907]
**What happened**:
The tests fail on rc0 - https://github.com/submariner-io/subctl/actions/runs/6146985075/job/16677451127

The reason is:
```
 ✗ Error parsing current subctl version: release is not in dotted-tri format
```

**What you expected to happen**:
The tests should work.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by skitt** [comment]
Fixed by #930.
