### ISSUE TITLE
submariner issue:  x509: “kube-apiserver” certificate is not trusted

### ISSUE THREAD

**Issue by mudit000** [submariner-io/subctl#93]
**What happened**:
A)I have two Mac Laptops L1 & L2..both are on same home network...
B)I have kind cluster running on each Laptop
L1-->Kind cluster 1
L2-->Kind cluster 2

I wanted to use submarier to establish connectivity between these two clusters using submariner..

I installed operator successfully
<img width="600" alt="image" src="https://user-images.githubusercontent.com/20608498/173340123-2f348c24-1e5c-4809-889d-34d02b38c5c8.png">

But getting error while joining broker
<img width="1510" alt="image" src="https://user-images.githubusercontent.com/20608498/173340264-26ac8c18-c5ca-4078-8054-770c9712c65e.png">

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):below
- Gather information (use `subctl gather`)below  
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/20608498/173342164-66597013-166b-48b7-9863-73c78fc2e774.png">

- Cloud provider or hardware configuration:local kind cluster
- Install tools:kind cluster
- Others:

**Comment by mudit000** [comment]
I am following this page https://piotrminkowski.com/2021/07/08/kubernetes-multicluster-with-kind-and-submariner/

**Comment by skitt** [comment]
Thanks for filing this!

Could you clarify the following?

* Where did you deploy the broker? L1 or L2?
* Were you able to join the cluster on the same machine, or did both L1 and L2 fail?
* What does the 192.168.1.154 IP address represent?

Could you run `subctl diagnose` and `subctl gather` on `kind-cluster-1` as well?

**Comment by mudit000** [comment]
Where did you deploy the broker? L1 or L2? -->Currently its only on L2
Were you able to join the cluster on the same machine, or did both L1 and L2 fail? i have still not started with L1...
What does the 192.168.1.154 IP address represent? this is api server IP

**Comment by mudit000** [comment]
> subctl diagnose

kind-cluster-1 currently donot have anything..as per the page link i shared..i have started with kind-cluster-2

**Comment by dfarrell07** [comment]
This may be related: https://github.com/submariner-io/subctl/issues/67

**Comment by dfarrell07** [comment]
@mudit000 Is this still an issue?

**Comment by dfarrell07** [comment]
Closing due to lack of response, feel free to re-open if it's still an issue.
