### ISSUE TITLE
Broker info retrieved using subctl command shows some differences with original file

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/subctl#953]
**What happened**:
When Submariner (0.16.0-rc1) is installed on OCP 4.14.0-rc0 deployments and we try `subctl recover-broker-info` command, it successfully recovers the broker-info.subm file. However, when I try diff with the original file, I see some (non-functional) differences. AFAIU the the retrieved file would work without any issues. 

I'm reporting this issue mainly to highlight that we are seeing some differences which was not the case when the same command was used with previous versions of OCP.

![Screenshot from 2023-09-27 21-46-09](https://github.com/submariner-io/subctl/assets/6574656/0b0e9784-5a3e-40a8-8508-ee71d45d628d)

![Screenshot from 2023-09-27 21-46-44](https://github.com/submariner-io/subctl/assets/6574656/e22290f5-36ef-4017-94b3-4a825bb9e3fc)

**Comment by tpantelis** [comment]
We serialize the token `Secret` resource as is as read from K8s. So it looks like something added a` legacy-token-not-used` label in between the time the broker was deployed and you did the recovery. During the recovery process it reads the `Secret` resource from K8s so the new file reflects that change. This is not an issue - the label added is probably something internal to OCP and is non-functional to submariner.

**Comment by sridhargaddam** [comment]
Yeah, as mentioned in the bug report, the differences should not affect the functionality. 

But its going to make it a bit difficult for us to check if the retrieved broker-info.subm is matching with the original file. For example, earlier, I used to take backup of the original broker-info.subm file and compare it with the retrieved one using the simple `diff` command and there used to be no differences. However, with OCP 4.14 (and maybe new K8s versions), we have to use `base64 -d` and compare individual fields.
