### ISSUE TITLE
Support changing repositories during upgrade

### ISSUE THREAD

**Issue by Jaanki** [submariner-io/subctl#955]
Current upgrade mechanism supports only version changes during upgrade process. The ask here is to also support repository change during an upgrade process.

Pros:
1. Will be helpful in scenarios where the images hosted has changed

Cons:
1. Images for all submariner components would need to be hosted to the new repository for this to work

**Comment by Jaanki** [comment]
@maayanf24 Will you be interested in taking a look at this one?

**Comment by dfarrell07** [comment]
I'm assuming we're talking about "From Quay to X"? Is there a situation where we hit this recently?

**Comment by dfarrell07** [comment]
We talked about this live on a call, as I recall these were the answers:

> I'm assuming we're talking about "From Quay to X"?

Yes

> Is there a situation where we hit this recently?

No, there wasn't, just thinking about possibilities and this was mentioned in the initial code review of the feature.
