### ISSUE TITLE
submariner components not upgraded after running upgrade

### ISSUE THREAD

**Issue by Jaanki** [submariner-io/subctl#971]
**What happened**:
After running `subctl upgrade --to-version 0.16.0` on the setup deployed with 0.16.0-rc1 images, all submariner components are not upgraded to 0.16.0. Only the operator image is upgraded.

```
$ subctl show versions
Cluster "cluster1"
 ✓ Showing versions 
COMPONENT                       REPOSITORY           CONFIGURED   RUNNING                     
submariner-gateway              quay.io/submariner   0.16.0-rc1   release-0.16-d1b6c9e194f8   
submariner-routeagent           quay.io/submariner   0.16.0-rc1   release-0.16-d1b6c9e194f8   
submariner-metrics-proxy        quay.io/submariner   0.16.0-rc1   release-0.16-d48224e08e06   
submariner-operator             quay.io/submariner   0.16.0       release-0.16-0807883713b0   
submariner-lighthouse-agent     quay.io/submariner   0.16.0-rc1   release-0.16-6f1d3f22e806   
submariner-lighthouse-coredns   quay.io/submariner   0.16.0-rc1   release-0.16-6f1d3f22e806   

Cluster "cluster2"
 ✓ Showing versions 
COMPONENT                       REPOSITORY           CONFIGURED   RUNNING                     
submariner-gateway              quay.io/submariner   0.16.0-rc1   release-0.16-d1b6c9e194f8   
submariner-routeagent           quay.io/submariner   0.16.0-rc1   release-0.16-d1b6c9e194f8   
submariner-metrics-proxy        quay.io/submariner   0.16.0-rc1   release-0.16-d48224e08e06   
submariner-operator             quay.io/submariner   0.16.0       release-0.16-0807883713b0   
submariner-lighthouse-agent     quay.io/submariner   0.16.0-rc1   release-0.16-6f1d3f22e806   
submariner-lighthouse-coredns   quay.io/submariner   0.16.0-rc1   release-0.16-6f1d3f22e806   
```

**What you expected to happen**:
All submariner components to be of version 01.6.0.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy Submariner version 0.16.0-rc1. Run `subctl upgrade --to-version 0.16.0`. Check the versions with `subctl show versions`.

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by maayanf24** [comment]
I've tested with `subctl 0.16.1` -> to version 0.16.2: 

all components got upgraded to 0.16.2,

`subctl version
subctl version: v0.16.1
[maafried@fedora submariner-operator]$ subctl upgrade --to-version 0.16.2
 ✓ Upgrading subctl from v0.16.1 to v0.16.2, replacing subctl 
Cluster "cluster1"
 ✓ Checking if the Broker is installed
 ✓ Upgrading the Broker to 0.16.2
 ✓ Setting up broker RBAC
 ✓ Deploying the Submariner operator 
 ✓ Created operator namespace: submariner-operator
 ✓ Deploying the broker 
 ✓ Upgrading the Connectivity component to 0.16.2 
 ✓ Upgrading Service Discovery to 0.16.2

Cluster "cluster2"
 ✓ Checking if the Broker is installed
 ✓ Checking if the Operator is installed
 ✓ Upgrading the Operator to 0.16.2 
 ✓ Created operator namespace: submariner-operator
 ✓ Upgrading the Connectivity component to 0.16.2 
 ✓ Upgrading Service Discovery to 0.16.2

[maafried@fedora submariner-operator]$ subctl version
subctl version: v0.16.1
[maafried@fedora submariner-operator]$ subctl show all
Cluster "cluster2"
 ✓ Detecting broker(s)
 ✓ No brokers found

 ✓ Showing Connections
GATEWAY                  CLUSTER    REMOTE IP    NAT   CABLE DRIVER   SUBNETS                        STATUS      RTT avg.     
cluster1-control-plane   cluster1   172.18.0.4   no    libreswan      100.66.0.0/16, 10.130.0.0/16   connected   190.404µs    

 ✓ Showing Endpoints
CLUSTER    ENDPOINT IP   PUBLIC IP       CABLE DRIVER   TYPE     
cluster2   172.18.0.6    147.235.207.9   libreswan      local    
cluster1   172.18.0.4    147.235.207.9   libreswan      remote   

 ✓ Showing Gateways
NODE                     HA STATUS   SUMMARY                               
cluster2-control-plane   active      All connections (1) are established   

 ✓ Showing Network details
    Discovered network details via Submariner:
        Network plugin:  kindnet
        Service CIDRs:   [100.67.0.0/16]
        Cluster CIDRs:   [10.131.0.0/16]

 ✓ Showing versions 
COMPONENT                       REPOSITORY           CONFIGURED   RUNNING                     ARCH    
submariner-gateway              quay.io/submariner   0.16.2       release-0.16-88f54d25ccfc   amd64   
submariner-routeagent           quay.io/submariner   0.16.2       release-0.16-88f54d25ccfc   amd64   
submariner-metrics-proxy        quay.io/submariner   0.16.2       release-0.16-3d7d32af4808   amd64   
submariner-operator             quay.io/submariner   0.16.2       release-0.16-d4284df96925   amd64   
submariner-lighthouse-agent     quay.io/submariner   0.16.2       release-0.16-847b34cf06d0   amd64   
submariner-lighthouse-coredns   quay.io/submariner   0.16.2       release-0.16-847b34cf06d0   amd64   


Cluster "cluster1"
 ✓ Detecting broker(s)
NAMESPACE               NAME                COMPONENTS                        GLOBALNET   GLOBALNET CIDR   DEFAULT GLOBALNET SIZE   DEFAULT DOMAINS   
submariner-k8s-broker   submariner-broker   service-discovery, connectivity   no          242.0.0.0/8      65536                                      

 ✓ Showing Connections
GATEWAY                  CLUSTER    REMOTE IP    NAT   CABLE DRIVER   SUBNETS                        STATUS      RTT avg.    
cluster2-control-plane   cluster2   172.18.0.6   no    libreswan      100.67.0.0/16, 10.131.0.0/16   connected   135.05µs    

 ✓ Showing Endpoints
CLUSTER    ENDPOINT IP   PUBLIC IP       CABLE DRIVER   TYPE     
cluster1   172.18.0.4    147.235.207.9   libreswan      local    
cluster2   172.18.0.6    147.235.207.9   libreswan      remote   

 ✓ Showing Gateways
NODE                     HA STATUS   SUMMARY                               
cluster1-control-plane   active      All connections (1) are established   

 ✓ Showing Network details
    Discovered network details via Submariner:
        Network plugin:  kindnet
        Service CIDRs:   [100.66.0.0/16]
        Cluster CIDRs:   [10.130.0.0/16]

 ✓ Showing versions 
COMPONENT                       REPOSITORY           CONFIGURED   RUNNING                     ARCH    
submariner-gateway              quay.io/submariner   0.16.2       release-0.16-88f54d25ccfc   amd64   
submariner-routeagent           quay.io/submariner   0.16.2       release-0.16-88f54d25ccfc   amd64   
submariner-metrics-proxy        quay.io/submariner   0.16.2       release-0.16-3d7d32af4808   amd64   
submariner-operator             quay.io/submariner   0.16.2       release-0.16-d4284df96925   amd64   
submariner-lighthouse-agent     quay.io/submariner   0.16.2       release-0.16-847b34cf06d0   amd64   
submariner-lighthouse-coredns   quay.io/submariner   0.16.2       release-0.16-847b34cf06d0   amd64   


[maafried@fedora submariner-operator]$ subctl version
subctl version: v0.16.1
[maafried@fedora submariner-operator]$ 

`

**Comment by maayanf24** [comment]
Another check: using `subctl 0.16.1` to upgrade to 0.16.0, results with same issue as original bug:

`subctl upgrade --to-version 0.16.0
Cluster "cluster1"
 ✓ Checking if the Broker is installed
 ✓ Upgrading the Broker to 0.16.0
 ✓ Setting up broker RBAC
 ✓ Deploying the Submariner operator 
 ✓ Created operator namespace: submariner-operator
 ✓ Deploying the broker 
 ✓ Upgrading the Connectivity component to 0.16.0 
 ✓ Upgrading Service Discovery to 0.16.0

Cluster "cluster2"
 ✓ Checking if the Broker is installed
 ✓ Checking if the Operator is installed
 ✓ Upgrading the Operator to 0.16.0 
 ✓ Created operator namespace: submariner-operator
 ✓ Upgrading the Connectivity component to 0.16.0 
 ✓ Upgrading Service Discovery to 0.16.0

[maafried@fedora submariner-operator]$ subctl show versions
Cluster "cluster1"
 ✓ Showing versions 
COMPONENT                       REPOSITORY           CONFIGURED   RUNNING                     ARCH    
submariner-gateway              quay.io/submariner   0.16.0-rc1   release-0.16-d1b6c9e194f8   amd64   
submariner-routeagent           quay.io/submariner   0.16.0-rc1   release-0.16-d1b6c9e194f8   amd64   
submariner-metrics-proxy        quay.io/submariner   0.16.0-rc1   release-0.16-d48224e08e06   amd64   
submariner-operator             quay.io/submariner   0.16.0       release-0.16-0807883713b0   amd64   
submariner-lighthouse-agent     quay.io/submariner   0.16.0-rc1   release-0.16-6f1d3f22e806   amd64   
submariner-lighthouse-coredns   quay.io/submariner   0.16.0-rc1   release-0.16-6f1d3f22e806   amd64   

Cluster "cluster2"
 ✓ Showing versions 
COMPONENT                       REPOSITORY           CONFIGURED   RUNNING                     ARCH    
submariner-gateway              quay.io/submariner   0.16.0-rc1   release-0.16-d1b6c9e194f8   amd64   
submariner-routeagent           quay.io/submariner   0.16.0-rc1   release-0.16-d1b6c9e194f8   amd64   
submariner-metrics-proxy        quay.io/submariner   0.16.0-rc1   release-0.16-d48224e08e06   amd64   
submariner-operator             quay.io/submariner   0.16.0       release-0.16-0807883713b0   amd64   
submariner-lighthouse-agent     quay.io/submariner   0.16.0-rc1   release-0.16-6f1d3f22e806   amd64   
submariner-lighthouse-coredns   quay.io/submariner   0.16.0-rc1   release-0.16-6f1d3f22e806   amd64   

[maafried@fedora submariner-operator]$ subctl version
subctl version: v0.16.1
`

**Comment by maayanf24** [comment]
After some more testing, it looks to me that the issue is not in `subctl` and could be in the version of 0.16.0 itself.
I think we can close this.
@Jaanki What do you think?

**Comment by skitt** [comment]
Most of this is caused by confusing version information embedded in the release images; see https://github.com/submariner-io/releases/issues/941 for details.

There is another related issue concerning default version handling, I’m still looking into that.

**Comment by maayanf24** [comment]
Since the problem is tracked in another issue, closing this one
